Repository lexik/LexikJWTAuthenticationBundle, pull requests merged in 2018-06, with the labels that each got.

#485 Add a `lexik:jwt:generate-token` command
  Command/GenerateTokenCommand.php
  DependencyInjection/Compiler/WireGenerateTokenCommandPass.php
  LexikJWTAuthenticationBundle.php
  Resources/config/console.xml
  Tests/Functional/Command/GenerateTokenCommandTest.php
  Tests/Functional/TestCase.php
  Tests/Functional/app/AppKernel.php
  Tests/Functional/app/config/GenerateTokenCommand/config.yml
Labels: Feature, Ready

#508 Replace namshi/jose by lcobucci/jwt
  DependencyInjection/Configuration.php
  DependencyInjection/LexikJWTAuthenticationExtension.php
  Encoder/DefaultEncoder.php
  Encoder/LcobucciJWTEncoder.php
  Resources/config/jwt_encoder.xml
  Resources/config/lcobucci.xml
  Resources/config/namshi.xml
  Resources/doc/1-configuration-reference.md
  Services/JWSProvider/DefaultJWSProvider.php
  Services/KeyLoader/OpenSSLKeyLoader.php
  Tests/Encoder/DefaultEncoderTest.php
  Tests/Functional/DependencyInjection/AutowiringTest.php
  Tests/Functional/DependencyInjection/LexikJWTAuthenticationExtensionTest.php
  Tests/Functional/app/config/autowiring.yml
  Tests/Functional/app/config/base_config.yml
  Tests/Functional/app/config/config_default.yml
  Tests/Services/JWSProvider/DefaultJWSProviderTest.php
  Tests/Services/KeyLoader/OpenSSLKeyLoaderTest.php
  Tests/Stubs/Autowired.php
  composer.json
Labels: Feature

#510 Rename UserProviderWithPayloadSupportsInterface => PayloadAwareUserProviderInterface
  Security/Guard/JWTTokenAuthenticator.php
  Security/User/JWTUserProvider.php
  Security/User/PayloadAwareUserProviderInterface.php
Labels: Enhancement
